safe-global/safe-config-service

- README.md
Closes #1 
You can read the formatted version of this branch here: https://github.com/gnosis/safe-config-service/blob/update_readme/README.md
> Add local development instructions to README

- src/safe_apps/tests/test_models.py
Adds tests to test the representation of the model instances
> Test model string representation

- src/safe_apps/tests/test_admin.py
- Add tests for `NetworkFilter`
> Add network filter tests

- .env.example
- src/config/settings.py
Closes #57 
- Sets default REST renderer to `rest_framework.renderers.JSONRenderer`
> Set default REST renderer

- src/config/urls.py
Closes #67 
- Adds `/check` endpoint that can be used to check the readiness for the service to receive requests
> Add /check endpoint

- nginx/templates/nginx.conf.template
- Updates the nginx configuration to match more closely the current transaction service production configuration
> Add production ready nginx config

- src/about/apps.py
- src/about/tests/test_views.py
- src/about/urls.py
- src/about/views.py
- src/config/settings.py
- src/config/urls.py
- src/version.py
Closes #103 
- Add `api/v1/about` which displays information about the service
> Add /about endpoint

- src/about/tests/test_views.py
- src/version.py
Preparation for the next release:
- Add theme information to `/chain` (#112)
- Add /about endpoint (#109)
- Add Transaction Service url to Chain (#106)
- Enable blank values for safe-app provider (#115)
- Remove route slicing from logger (#111)
- Add trailing slash to chains/id/ endpoint (#110)
> Bump service version to 1.1.0

- src/about/tests/test_views.py
- src/version.py
Preparation for the next release:
- #120
- #122 
- #124 
- #128 
- #130
> Bump service version to 1.2.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v1.3.0...bump-service-version-1-4-0
> Bump service version to 1.4.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v1.4.0...bump-version-2-0-0
> Bump service version to 2.0.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.0.0...bump-service-version-2-0-1
> Bump service version to 2.0.1

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.0.1...bump-service-version-2-0-2
> Bump service version to 2.0.2

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.0.2...bump-service-2-0-3
> Bump service version to 2.0.3

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.0.3...main
> Bump service version to 2.1.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.1.0...bump-service-2-2-0
> Bump service version to 2.2.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.2.0...bump-service-version-2-3-0
> Bump service version to 2.3.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/main...release-2-3-1
> Bump service version to 2.3.1

- src/about/tests/test_views.py
- src/chains/migrations/0025_alter_chain_currency_logo_uri.py
- src/chains/models.py
- src/version.py
- v2.3.1 was released (https://github.com/gnosis/safe-config-service/releases/tag/v2.3.1) and is ready to be merged to `main`
> Add 2.3.1 release changes

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.3.1...main
> Bump service version to 2.4.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.5.2...bump-service-version
> Bump service version to 2.5.3

- src/chains/signals.py
- src/chains/tests/factories.py
- src/chains/tests/test_signals.py
- Trigger the CGW `/flush` endpoint when a `Feature` or `Wallet` is created, updated or deleted
> Trigger CGW hook on Wallet and Feature update

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.5.3...bump-service-version-2-6-0
> Bump service version to 2.6.0

- src/chains/tests/test_views.py
- src/chains/urls.py
- src/chains/views.py
Closes #269 
Added support for fetching `Chains` using the `shortName`
> Retrieve `Chain` by `short_name`

- src/chains/tests/test_views.py
Removed `test_match` as it was identical to `test_json_payload_format`
> Removed redundant test

- .github/workflows/test.yml
- mypy.ini
- src/safe_apps/admin.py
- src/safe_apps/apps.py
- src/safe_apps/migrations/0001_initial.py
- src/safe_apps/models.py
- src/safe_apps/serializers.py
- src/safe_apps/signals.py
- src/safe_apps/tests/factories.py
- src/safe_apps/tests/test_admin.py
- src/safe_apps/tests/test_models.py
- src/safe_apps/tests/test_views.py
- src/safe_apps/views.py
- Add types to `safe-apps` app
- Check `safe-apps` using `--strict` mode in Github Actions
> Integrate mypy in safe-apps app

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.6.0...bump-service-version-2-7-0
> Bump service version to 2.7.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.7.0...main
> Bump service version to 2.7.1

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.7.1...main
> Bump service version to 2.7.2

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.7.2...main
> Bump service version to 2.8.0

- src/chains/signals.py
- src/chains/tests/test_signals.py
- Triggers the CGW `/flush` endpoint for `Chains` whenever there's an update to a `GasPrice`
> Trigger CGW /flush on GasPrice updates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
These are the same issue templates currently being used in the [CGW](https://github.com/gnosis/safe-client-gateway/tree/main/.github/ISSUE_TEMPLATE)
> Added the issue templates we have in the CGW

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.8.1...main
> Bump service version to 2.9.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.9.0...release-2.9.1
> Bump service version to 2.9.1

- src/chains/tests/test_views.py
- src/chains/views.py
- Change Chains pagination limit from `100` to `20`
> Change chains pagination max_limit to 20

- .github/workflows/cla.yml
- Adds CLA Action to the `safe-config-service`
> Add CLA action

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/gnosis/safe-config-service/releases/tag/v2.9.2
> Bump service version to 2.9.2

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/releases/tag/v2.9.3
> Bump service version to 2.9.3

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/releases/tag/v2.9.4
> Bump service version from 2.9.3 to 2.9.4

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/releases/tag/v2.9.5
> Bump service version from 2.9.4 to 2.9.5

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.9.5...release-3.10.0
> Bump service version from 2.9.5 to 2.10.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.10.0...release-2.11.0
> Bump service version from 2.10.0 to 2.11.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.12.0...release-2.13.0
> Bump service version from 2.12.0 to 2.13.0

- src/about/tests/test_views.py
- src/version.py
Changelog: https://github.com/gnosis/safe-config-service/compare/v2.13.0...bump-version-2.14.0
> Bump service version from 2.13.0 to 2.14.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/gnosis/safe-config-service/releases/tag/v2.15.0
> Backmerge release 2.15.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.16.0
> Backmerge release 2.16.0

- .env.example
- src/config/settings.py
- src/safe_apps/admin.py
- src/safe_apps/serializers.py
- src/safe_apps/tests/test_views.py
- Removes `SAFE_APPS_TAGS_FEATURE_ENABLED` as this feature is now being used by the clients in production
> Remove SAFE_APPS_TAGS_FEATURE_ENABLED flag

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.19.0
> Backmerge release 2.19.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.20.0
> Backmerge release 2.20.0

- .github/workflows/cla.yml
- Add users to cla and update cla url to new url
> Add users to cla file and update cla url

- .env.example
Closes #557
- Add POSTGRES_PASSWORD to environment example file
> Enable POSTGRES_PASSWORD in environment example file

- .github/workflows/test.yml
- Dockerfile
Closes #250
- Install python wheels in dockerfile
> Add python wheels to dockerfile

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.21.0
> Backmerge release 2.21.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.22.0
> Backmerge release 2.22.0

- requirements.txt
- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.23.0
> Backmerge release 2.23.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.24.0
> Bump service version from 2.23.0 to 2.24.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.25.0
> Backmerge release 2.25.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.26.0
> Backmerge release 2.26.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.27.0
> Backmerge release 2.27.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.28.0
> Backmerge release 2.28.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.30.0
> Backmerge release 2.30.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.31.0
> Backmerge release 2.31.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.32.0
> Backmerge release 2.32.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.33.0
> Backmerge release 2.33.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.34.0
> Backmerge release 2.34.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.35.0
> Backmerge release 2.35.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.36.0
> Backmerge release 2.36.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.37.0
> Backmerge release 2.37.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.38.0
> Backmerge release 2.38.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.40.0
> Backmerge release 2.40.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.41.0
> Backmerge release 2.41.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.42.0
> Backmerge release 2.42.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.43.0
> Backmerge release 2.43.0

- src/chains/serializers.py
- src/safe_apps/serializers.py
Fixes swagger not loading because of Serializer name conflict
> Add meta `ref_name` to `Feature` serializers

- src/safe_apps/admin.py
I forgot to include features to admin in https://github.com/safe-global/safe-config-service/pull/756, this PR adds it
> Feature: Add Safe App features to admin

- src/config/swagger_info.py
- Remove "Gnosis" from the Swagger title
> Update Swagger title

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.44.0
> Backmerge release 2.44.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.45.0
> Backmerge release 2.45.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.47.0
> Backmerge release 2.47.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.48.0
> Backmerge release 2.48.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.49.0
> Backmerge release 2.49.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.51.0
> Backmerge release 2.51.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.52.0
> Backmerge release 2.52.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.53.0
> Backmerge release 2.53.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.54.0
> Backmerge release 2.54.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.55.0
> Bump service version from 2.54.0 to 2.55.0

- src/config/swagger_info.py
Removes the contact field from the Swagger interface
> Remove contact field from Swagger

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.56.0
> Backmerge release 2.56.0

- src/about/tests/test_views.py
This PR aims to add detection for broken Swagger UI views.
- Detects issues with swagger breaking
- Related to https://github.com/safe-global/safe-config-service/pull/887
(Thanks to @Uxio0 for the original implementation)
> Add swagger UI view tests

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.58.0
> Backmerge release 2.58.0

- requirements.txt
Reverts safe-global/safe-config-service#914
> Revert "Bump safe-eth-py[django] from 5.5.0 to 5.6.0"

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.62.0
> Backmerge release 2.62.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.63.0
> Backmerge release 2.63.0

- .dev.env
- src/chains/signals.py
- src/chains/tests/test_signals.py
- src/clients/safe_client_gateway.py
- src/config/settings.py
- src/safe_apps/signals.py
- src/safe_apps/tests/test_signals.py
This reverts commit 77d0ec228ede16e3c20f6f95d3fa1ab3a26bf421.
> Revert "Support a second Client Gateway URL (#900)"

- .dev.env
- src/about/tests/test_views.py
- src/chains/signals.py
- src/chains/tests/test_signals.py
- src/clients/safe_client_gateway.py
- src/config/settings.py
- src/safe_apps/signals.py
- src/safe_apps/tests/test_signals.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.63.1
> Backmerge release 2.63.1

- .dev.env
- src/about/tests/test_views.py
- src/clients/safe_client_gateway.py
- src/config/settings.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.63.2
> Backmerge release 2.63.2

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.64.0
> Backmerge release 2.64.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.70.0
> Backmerge release 2.70.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.71.0
> Backmerge release 2.71.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.73.0
> Backmerge release v2.73.0

- src/about/tests/test_views.py
- src/version.py
Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.75.0
> Backmerge release 2.75.0

- .github/workflows/cla.yml
- Changes `branch` to `main` in the CLA Assistant Github Action.
> Fix bad branch in cla.yml
