safe-global/safe-config-service

.github/workflows/test.yml

Closes #4 
- Execute Github Action on PR event (instead of push+pr event which would trigger the action twice on pull requests)

Run Github Actions on PR trigger

---

.flake8
src/safe_apps/serializers.py
src/safe_apps/tests/test_views.py

Closes #10 
- The provider info is now serialized on the JSON response for each safe-app. Eg.:
```json
{
"url": "https://cloudflare-ipfs.com/ipfs/QmRb2VfPVYBrv6gi2zDywgVgTg3A19ZCRMqwL13Ez5f5AS",
"name": "Balancer Exchange",
"icon_url": "https://cloudflare-ipfs.com/ipfs/QmRb2VfPVYBrv6gi2zDywgVgTg3A19ZCRMqwL13Ez5f5AS/logo512.png",
"description": "Exchange tokens using the Balancer DEX",
"networks": [
1
],
"provider": {
"url": "https://balancer.finance",
"name": "Balancer Labs"
}
}
```

Serialize Provider Info

---

requirements-dev.txt
src/safe_apps/tests/factories.py
src/safe_apps/tests/test_views.py

Closes #9 
- Adds a factory for `Provider` and `SafeApp` so that test data can be generated more easily

Use FactoryBoy for generating test data

---

src/safe_apps/admin.py

Closes #11 
- Add `list_display`, `list_filter`, `search_fields` and `ordering` to the admin pages of `SafeApp` and `Provider`
- Add `NetworksFilter` to provider a filter over the array of networks for each app
* Since each `SafeApp` contains a list of networks, this list needs to be flattened and converted to a set
- Use `@admin.register` decorator for `SafeApp` and `Provider`

Improve admin display for Provider and SafeApp

---

.flake8
requirements-dev.txt
run
src/config/asgi.py
src/config/settings.py
src/config/urls.py
src/config/wsgi.py
src/manage.py
src/safe_apps/admin.py
src/safe_apps/apps.py
src/safe_apps/migrations/0001_initial.py
src/safe_apps/models.py
src/safe_apps/serializers.py
src/safe_apps/tests/factories.py
src/safe_apps/tests/test_views.py
src/safe_apps/urls.py
src/safe_apps/views.py

Closes #13 
- Adds Black code formatter – https://black.readthedocs.io/en/stable/
- Applied the formatting to the project
- Updated `flake8` config to be compatible with Black – https://black.readthedocs.io/en/stable/compatible_configs.html#flake8
- Adds Black check to the CI pipeline – Note that this does not automatically format any code. Code should be formatted on the user side either manually or by running `black src/` to apply the suggestions automatically

Add Black code style formatter

---

.pre-commit-config.yaml
README.md
requirements-dev.txt

Part of #19 
- Adds a pre-commit hook to run `Black` on changed files – to install the hook, run `pre-commit install`
- Updates documentation on the tools used for development

Add Black pre-commit hook

---

.env.example
docker-compose.yml
nginx/templates/nginx.conf.template
src/config/gunicorn.py

Closes #22 
- Extract port variables to the `.env` file
- Use Nginx templating system
* This allows that one template of a nginx configuration with environment variables correctly generates a configuration with those environment variables set
* The nginx image will look for those templates in the image location `/etc/nginx/templates`
* The `NGINX_ENVSUBST_OUTPUT_DIR` is an environment variable used by nginx – the path set here is the path where the generated configs (with the environment variables replaced) will be stored

Use Nginx templates to replace environment variables

---

.env.example
README.md
docker-compose.override.yml.ci
run

This is part of a review of making the configuration production ready by default. It was, for the most part, production ready already.
Some relevant keys like `SECRET_KEY`, `POSTGRES_USER` and `POSTGRES_PASSWORD` do not have any defaults and require to be setup – the goal is to avoid having a default set into a production build accidentally.
Given that the images rely both on the `.env` file and these variables:
- While developing, we can just set these variables on the `.env` file (for practical reasons some defaults are provided in a comment)
- In the CI, these variables are set by overriding the environment via ` docker-compose.override.yml.ci` – (this can also be applied for local development)

Remove defaults for some production environment variables

---

.github/workflows/test.yml

- The Github Action is now triggered on a `push` event for any branch
- This allows branches that do not have any Pull Request open to get feedback on the current status of the build before opening the Pull Request
Sidenote: I took into consideration the discussion here https://github.com/gnosis/safe-config-service/pull/5#discussion_r622101396

Run Action on push event on any branch

---

.env.example
src/config/middleware.py
src/config/settings.py

Closes #26 
- Add a Logging middleware – this middleware logs endpoint request calls to `INFO`
- Add Django logging settings
* A `root` logger that applies the configuration to loggers which are not declared in this dictionary. Default logging level is `INFO` (can be changed by setting `ROOT_LOG_LEVEL`)
* A `LoggingMiddleware` that logs view requests to `INFO`. It currently logs the HTTP method used, the route and paht, the time that it took to process the request and the status of the response.

Add Logging middleware

---

run

- Propagate return code of each sub-command to the pipeline (by default it was taking the last one executed, in this case the tests)
- The `-eo pipefail` set the pipeline to exit earlier if if a return code is `>0` (ie.: not successful)

Propagate subcommand failure return code

---

src/safe_apps/tests/test_views.py
src/safe_apps/views.py

Closes #28 
- Cache `safe-apps` endpoint for 1h
- Update tests that do not required caching to use `DummyCache`
- Add test to test caching
- It seems that adding view caching is relatively straightforward with `cache_page` but removing the cache entry when new data is added/updated/deleted seems to be complex
- The complexity comes from how Django generates the keys for cache entries they are based on the request that was made, the environment where the request was made, and header properties – https://github.com/django/django/blob/ca9872905559026af82000e46cde6f7dedc897b6/django/utils/cache.py#L347-L366
- Correctly recreating the key is possible as the information is deterministic but it'd be a custom solution on our side that might not work on later versions. Given this I decided to not …

Cache GET /safe-apps/ endpoint

---

src/config/settings.py
src/safe_apps/apps.py
src/safe_apps/signals.py
src/safe_apps/tests/test_views.py
src/safe_apps/views.py

Closes #31 
- Add `safe-apps` cache (which is a `LocMemCache`)
- Add signal which is triggered on `SafeApp` or `Provider` updates
- Test now checks if the response header `Cache-Control` returns the correct value

Use different cache for view. Invalidate on update

---

.dockerignore
.github/workflows/publish-staging.yml

- Deploys production docker image to Docker Hub when the `main` branch is updated
- Cache docker layers with `cache-from` and `cache-to`
- Ignore files which are not required for the docker web image

Add Docker deploy step for main branch

---

.github/workflows/test.yml

Adding the `continue-on-error` to avoid an external service being down and blocking the PR

Continue pipeline if coverage upload fails

---

.github/workflows/publish-staging.yml
Dockerfile
docker-compose.yml

- Previously the Dockerfile was split into 2 stages:
* `python-base` – base dependencies to build the project + installation of production dependencies
* `development` – base + development dependencies
One issue here is that `python-base` didn't copy the application to the image and this was the stage that was being published to Docker Hub. To fix that issue and to make each stage more explicit these are the new stages:
* `production` – base dependencies to build the project + copy of the application + production dependencies
* `development` – production + installation of development dependencies

Add missing steps to production image

---

Dockerfile
docker-compose.yml
docker-entrypoint.sh

Closes #43 
- Adds a Docker `ENTRYPOINT` to the production image (also applies to the dev image).
- The entrypoint performs the following:
* Executes migrations
~* Loads initial fixture data using `manage.py loaddata` (this does not override current data)~
* Launches app with `Gunicorn`

Add entrypoint script

---

.env.example
src/config/settings.py

- To match the environment variable set in the transaction service and the deployment settings, `ALLOWED_HOSTS` is now `DJANGO_ALLOWED_HOSTS`

Change ALLOWED_HOSTS to DJANGO_ALLOWED_HOSTS

---

.env.example
docker-compose.yml
docker-entrypoint.sh
nginx/templates/nginx.conf.template

Closes #59 
- Use Unix socket to bind the application
- This avoids Nginx requiring to know the name registered of the container/service which is running the Gunicorn app

Use Unix socket in addition to TCP to bind application

---

.env.example
requirements.txt
src/config/settings.py
src/safe_apps/tests/test_views.py

Closes #64 
- JSON keys in response payloads are now in camel case
- Add `djangorestframework-camel-case` – this renderer class is responsible for converting the keys to camel case (it is now the default renderer)
- Would this dependency be ok or shall we go with an internal solution? I saw already this dependency being used here so I guess we can continue using it: https://github.com/gnosis/safe-transaction-service/blob/cda755631cadbe03f2cc5e792d80f721212556c8/requirements.txt#L18

Format JSON response keys to camel case

---

docker-entrypoint.sh
src/config/settings.py

Closes #75 
- Collect static files when the web image is deployed with `manage.py collectstatic`
- Copy collected files folder (`staticfiles/`) to `${DOCKER_NGINX_VOLUME_ROOT}`

Serve static files with Nginx

---

.coveragerc
requirements.txt
src/config/settings.py
src/config/swagger_info.py
src/config/urls.py
src/safe_apps/views.py

Closes #73 
- Adds Swagger specification page to the project with `drf-yasg`
- Provide default Swagger Info in Django Settings file (info under `swagger_info.py`)

Add Swagger

---

requirements.txt
src/config/settings.py

Closes #79 
- Adds CORS headers
- Allow any origin to request the resources under `^/api/.*$`

Add CORS headers

---

src/chains/tests/test_views.py
src/chains/views.py
src/safe_apps/views.py

Closes #91 
- Adds pagination to `api/v1/chains`
- Default pagination size is `10`, max pagination size is `10`
Pagination payload:
```javascript
{
"count": 1,
"next": null,
"previous": null,
"results": [
{
"chainId": "123123",
"chainName": "Test",
"rpcUrl": "http://example.com",
"blockExplorerUrl": "http://example.com",
"nativeCurrency": {
"name": "Ether",
"symbol": "ETH",
"decimals": 18
}
}
]
}
```

Add pagination to /chains endpoint

---

src/config/urls.py
src/safe_apps/tests/test_views.py
src/safe_apps/urls.py

Closes #89 
- Change `/api/v1/safe-apps` reverse resolution from `v1:safe-apps` to `safe-apps:list`

Reverse /safe-apps resolution to safe-apps:list

---

src/chains/views.py

- Remove unused `@swagger_auto_schema` annotation from `ChainsListView`

Remove unecessary swagger annotation

---

src/chains/tests/factories.py
src/chains/tests/test_views.py
src/chains/urls.py
src/chains/views.py

- Adds `/chains/<id>` – this endpoint returns the chain with the `id` set in the path. `404` is returned if the chain was not found
- Use `response.data` in tests to avoid testing the json format – there is already a test validating the format of the payload – `ChainJsonPayloadFormatViewTests.test_json_payload_format`
- `ChainFactory` now returns a `pyint`. This matches better was is stored by the `Chain` model

Add /chains/<id> endpoint

---

.github/workflows/publish-tag.yml

Closes #97 
- Trigger Docker image publishing on releases – the `released` type is only triggered when:
* a release is published, or 
* a pre-release is changed to a release
* ` on: release` Is not triggered for draft releases
- Retrieve tag version with `${{ github.event.release.tag_name }}`

Add publish-tag Github Action

---

src/chains/tests/test_views.py
src/chains/urls.py
src/config/settings.py
src/config/urls.py
src/safe_apps/tests/test_views.py
src/safe_apps/urls.py

Closes #107 
- Url paths that require versioning are now under a nested namespace: `v1`
- This means that `chains` and `safe-apps` apps are now under `v1:chains` and `v1:safe-apps` respectively 
- Enable request versioning with `rest_framework.versioning.NamespaceVersioning`

Use nested namespaces for versioning

---

src/chains/urls.py

- `/api/v1/chains/<id>/` should now return the correct response – `200` if the `id` exists, instead of a `404`
- `/api/v1/chains/<id>` (no trailing slash) now redirects (`HTTP 301`) to the endpoint with the trailing slash. The configuration that enables this behaviour is `APPEND_SLASH` which is enabled by default

Add trailing slash to chains/<id>/ endpoint

---

src/config/middleware.py

Remove Logging Middleware route slicing – it was removing first character of the route which is not the intended behaviour

Remove route slicing from logger

---

src/chains/serializers.py
src/chains/tests/test_views.py

- In the Json response of `/chains`, the `gasPriceOracle` is now `null` if its url (`gasPriceOracle.url`) is also `null`
- This was done in order to simplify the validation of some fields on the client side
Before:
```javascript
{
...
"gasPriceOracle": {
"url": null,
"parameter": null
}
}
```
After:
```javascript
{
...
"gasPriceOracle": null
}
```

Set gasPriceOracle to null if its url is null

---

Dockerfile

- Remove Docker image minor version declaration
- Image should be resolved to the latest `alpine` release of `Python 3.9`

Remove image minor version declaration

---

src/chains/tests/test_views.py
src/chains/views.py

Closes #144 
- Increased `/chains` pagination max limit to `100`

Increase Chains pagination limit

---

Dockerfile

- Add `autoconf`, `automake` and `libtool` which are required to build `coincurve`

Add missing coincurve build dependencies

---

src/chains/tests/factories.py
src/safe_apps/tests/factories.py

- Use `factory.Sequence` to generate unique values for the primary keys of `Chain` and `SafeApp`
- Previously there was a chance that some tests could fail randomly due to the duplicate ids generated by the Factories

Use factory.Sequence for unique values

---

requirements-dev.txt
requirements.txt

- The latest web3 interface is not compatible with `ethereum_client.py` from `gnosis-py` (`transaction_formatter` is no longer available under `web3._utils.method_formatters`)

Force web3.py version to 5.18

---

src/chains/models.py

- Fixes an issue when saving an invalid form where when the Gas Price (fixed) and Gas Price oracle were not set (or were both set) would crash the application
- The reason is that the validation error map was referencing the wrong field `gas_price_fixed` instead of `gas_price_fixed_wei`
```
ValueError: 'ChainForm' has no field named 'gas_price_fixed'
```

Fix validation error field reference

---

src/chains/models.py
src/chains/tests/test_models.py

- When the oracle url is set then the oracle parameter should also be required
```javascript
{
"type": "oracle",
"url": <string>, // required
"gasParameter": <string>, // required
"gweiFactor": <stringified-number>, // optional
}
```

Oracle parameter is required if oracle is set

---

.gitignore
run

What this PR does:
- add vscode settings dir and `staticfiles` to `.gitignore` improvements for vscode
- (?) fix manage.py directory in the `run` script

Chore: Fix script to run commands inside docker container, extend .gitignore

---

requirements.txt

- Bump `gnosis-py` from 3.1.13 to 3.1.14
- `web3` is no longer required to be set since the new version of `gnosis-py` correctly sets the version range

Bump gnosis-py from 3.1.13 to 3.1.14

---

src/chains/migrations/0019_add_safe_apps_rpc.py

- Fix `TypeError: <lambda>() takes 0 positional arguments but 2 were given`
- The reverse function should take two positional arguments and should be declared in the lambda
- This issue prevents migration `0019` to be able to reverse

Fix migration reverse lambda args

---

.env.example
requirements-dev.txt
requirements.txt
src/chains/apps.py
src/chains/signals.py
src/chains/tests/test_signals.py
src/config/settings.py

Closes #173 
- Client Gateway hook implementation – this hook is triggered when a `Chain` is updated, created or deleted
- Add two new environment variables: one for the client gateway url (`CGW_URL`) and another one for the flush token (`CGW_FLUSH_TOKEN`)

Add CGW Chains webhook

---

.github/workflows/test.yml

- Add step to CI to check if there are any migrations that should've been created and were not created (without creating them)

Check pending Django migrations in CI

---

docker-compose.yml

- `POSTGRES_PORT` should be used only for the host port mapping
- Using `POSTGRES_PORT` for the container port would map it to a port where the `db` is not running

Use POSTGRES_PORT only for host port

---

Dockerfile

Since the introduction of `Pillow` in da146ef, additional build dependencies are required which were not present in the `Dockerfile` – https://pillow.readthedocs.io/en/latest/installation.html#building-on-linux

Add Pillow build dependencies to Dockerfile

---

Dockerfile
docker-entrypoint.sh

- Use `python-slim` instead of `python-alpine` as a base image
- Even though alpine is usually smaller, due to the lack of installed dependencies we would have to manage manually which dependencies were required for building the project and which ones were required for runtime
- This can be quite cumbersome due to the number of dependencies required by imaging libraries like `Pillow` which many of those were not present in the `alpine` image
**Non compressed sizes:**
|   |  Before (alpine) | After (slim)  |  % decreased |
|---|---|---|---|
|  production |  842MB  |  333MB | ~ 60%  |
| dev              |  867MB  |  371MB  |   ~ 57% |

Use python:3.9-slim as base image

---

src/chains/tests/test_signals.py

The new release of `responses` (https://github.com/getsentry/responses/releases/tag/0.14.0) moved `responses.json_params_matcher` to `responses.matchers.json_param_matcher` so `responses.json_params_matcher` is now deprecated.

Migrate to responses.matchers.json_params_matcher

---

src/chains/migrations/0025_alter_chain_currency_logo_uri.py
src/chains/models.py

- Set `max_length` of `currency_logo_uri` to `255` (max allowed by db)
- When the migration was applied with the production data, it raised the following exception `psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)`
- This issue is related with the default `max_length` of the `ImageField` (which is `100`) and a production value had an `ImageField` with more than `100` characters

Fix currency_logo_uri field length issue

---

src/config/settings.py

- Application was not compatible with nginx paths. Now FORCE_SCRIPT_NAME can be set
as an environment variable to add a base path for all the project
- Closes #242

Add force script name for nested paths on nginx

---

src/chains/admin.py

- Add `FeatureInline` and `WalletInline` to expose the `through` model of `Feature` and `Wallet` respectively on `ChainAdmin`
- This allows to easily add, change and remove the relationships between `Wallet` and `Chain` and `Feature` and `Chain`
This is an example of the admin view of a specific chain:

Add Wallet and Feature inlines to ChainAdmin

---

src/chains/tests/test_signals.py

When the tests were created, `Wallet` had `name` instead of `key` but it was then changed to `key` on the `main` branch so these tests no longer pass.

Fix test_signals wallet.key reference

---

.github/workflows/test.yml
docker-compose.yml

- We are using Postgres 13 in production so we should use the same version when testing locally with `docker compose`

Use Postgres 13 in docker compose

---

.flake8
.pre-commit-config.yaml

- Adds `flake8` as a pre-commit hook. `flake8` was already being checked by the CI but this should provide more convenience when we want to run all the commit checks in one go locally
- Remove `extend-ignore` and `exclude` rules from `flake8`. Current source is already compliant without excluding these rules.

Add flake8 commit hook

---

.coveragerc
.github/workflows/test.yml

- Omit every test folder from the coverage report
- Set `src` as the default to measure coverage

Omit tests in coverage report

---

.dockerignore

- `mypy.ini` was present in the Docker image even though it's only required when running `mypy` (locally or CI)

Add mypy.ini to .dockerignore

---

src/chains/admin.py

Closes #354 
- Add `GasPriceInline` to `ChainAdmin` – this allows editing the respective gas prices from the Chain Admin interface

Add GasPriceInline to ChainAdmin

---

src/about/tests/test_views.py
src/chains/tests/test_views.py
src/chains/views.py
src/version.py

- Increase the default pagination limit from `10` to `20`
- This mitigates an issue where `safe-react` would only request the default number of chains even if more than `10` are available

Set default chains pagination limit to 20

---

.env.example
requirements.txt
src/config/admin.py
src/config/settings.py

Closes #341 
- Enable OTP for admin access – this setting can be enabled via `DJANGO_OTP_ADMIN` (default `true`)
- If `DJANGO_OTP_ADMIN` is set to `true` then a new admin (`OTPAdminConfig`) is plugged in and logging in requires an OTP token
- If `DJANGO_OTP_ADMIN` is set to `false` then the default Django admin is used – this is useful when developing locally for example
- When deploying the OTP admin, current admins will be "locked out" of their account because an OTP will be required to login, to get around this issue a static OTP can be configured for one of the admins to do the initial setup via `python src/manage.py addstatictoken <username>`. Once every admin has the OTP set then the static token can be removed

Set OTP for admin access

---

src/safe_apps/tests/test_views.py
src/safe_apps/views.py

This PR fixes:
- In my previous PR for access control for Safe Apps I forgot to include client_url param to swagger parameters
- (nit) Aligns naming between chainId param and the variable naming
- convert `client_url` to camelCase in tests/views

Add GET /safe-apps client_url param to swagger, align chainId param/variable naming

---

requirements.txt
src/config/settings.py

- Bump Django to version 4 – Release Notes: https://docs.djangoproject.com/en/4.0/releases/4.0/
- Remove `USE_L10N` from `settings.py` – the default value is now `True`
* Additionally, this setting is deprecated: _"Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale"_ – https://docs.djangoproject.com/en/4.0/ref/settings/#use-l10n

Bump Django from 3.2.10 to 4.0

---

src/chains/models.py
src/safe_apps/tests/test_views.py
src/safe_apps/views.py

When writing tests for the safe-client-gateway, I discovered that if you specify an empty `clientUrl` query param, the apps would still get filtered by an empty string. In this PR:
- add a check for an empty `clientUrl` param and extend the test
- rename the variable for `chainId` param from `network_id` to `chain_id` to match the param name and use the same approach for client_url
- Use `Union` for type definitions instead of `|` to remove hard requirements on python 3.10+

Bug: apps are filtered by the client if clientUrl param is empty

---

src/safe_apps/tests/test_views.py

- Currently there's no sorting in place for the safe-apps endpoints so there's no guarantee on how the different safe-apps will be returned
- Use `self.assertCountEqual` to compare the entries present in the response payload regardless of their order

Fix safe-apps view tests (sorting)

---

.github/workflows/test.yml

- Since we are getting external contributions, we need to enable these events so that the actions can run on PRs coming from forks.

Run Github Action on PR events

---

.env.example
src/config/settings.py

Based on https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins I could use this setting and I don't think it harms being here.

support for trusted csrf origins

---

src/chains/signals.py
src/chains/tests/test_signals.py

- Migrate to the new flush route – `/v2/flush`
- This route no longer requires the token to be set in the path. Instead, the token should be set in an `Authorization` header with the value of `Basic <token>`

Migrate to /v2/flush

---

src/safe_apps/signals.py
src/safe_apps/tests/test_signals.py

- Invalidate the Safe Client Gateway cache when a `SafeApp` is added, updated or deleted
- The payload used in `flush` endpoint refers to `Chains` but this is because there's no distinction on the caching layer of the Safe Client Gateway between `Chain` and `SafeApp`

Invalidate client gateway cache on safe-app update

---

src/safe_apps/tests/test_views.py
src/safe_apps/views.py

See https://github.com/safe-global/safe-client-gateway/issues/855
- Add query parameter to `SafeAppsListView` which matches the `url` field of a `SafeApp`
- The url needs to be an exact match ie.: the protocol, path, any slash, query parameter, etc. need to be the same
```javascript
GET /api/v1/safe-apps/?url=https%3A%2F%2Fapp.aave.com
[
{
"id": 1,
"url": "https://app.aave.com",
"name": "Aave v2",
...
]
```

Add url filter for SafeApps

---

.env.example

This reverts commit 37442835991425874e57027e02d0a07fa2ff0211.
The `.env.sample` file contains production ready defaults. If this needs to change it'd be a bigger change than just this field. See: https://github.com/safe-global/safe-config-service/blob/eca3fa3f5474cbb7a9273592af25fcea8c54ee71/.env.example#L1-L6

Revert "Uncomment POSTGRES_PASSWORD on environment example file (#558)"

---

.github/workflows/test.yml

- We delegate caching to `actions/cache@v3` as long dependencies are installed in `~/.cache/pip`

Remove --no-cache-dir option from Github Action

---

.env.example

Closes #560
- Fix CSRF validation when running with `nginx` container locally
- With the default settings provided in `.env.sample` and using Docker with the `nginx` container, `POST` requests fail (this can be verified by trying to login in the admin interface)
- This is part of the effort to provide development-ready defaults

Set localhost as trusted origin in sample .env

---

.dev.env
.dockerignore
README.md
docker-compose.yml
src/config/settings.py

- In order to streamline the development process, the default environment variables were changed from being production-ready to being development-ready
- This includes variables:
* `SECRET_KEY` – which has the default value of `random-dev-key`
* `DEFAULT_FILE_STORAGE` – which has the default value of `django.core.files.storage.FileSystemStorage` (AWS setup is no longer required)
* The Host of the database is now `localhost` – we aim to support mainly running the application locally while the DB can be behind a docker image
* `DEBUG` is now set to `true` by default
- Rename `.env.example` to `.dev.env` – this file will be used mostly by Docker Compose.
- Overall the goal of the changes that were made were mostly around having the development environment already setup and ready to be worked …

Use development settings as default

---

.github/workflows/test.yml

- We took a look on the different official dockerhub images (https://hub.docker.com/search?q=&type=image&image_filter=official) and they all follow the same "de facto" standard of setting `latest` to the last release of the application.
- They use `stable` for older versions or LTS, and in our case we don't have that and we want users running the last versions of our services.
- With this `latest` tag it will be easy for users to be updated and not having to manually update versions (like in https://github.com/safe-global/safe-infrastructure)
- Also make docker staging/release pushes different jobs

Set `latest` docker tag on releases

---

.github/workflows/test.yml

- Changes `gnosispm` to `safeglobal` when building and pushing Docker images

Update org in docker images

---

src/safe_apps/tests/test_views.py
src/safe_apps/views.py

- Closes #697
I provided a quick PR for this, but the right solution would be using Django filtering (I don't know if it's worth it to migrate now): https://www.django-rest-framework.org/api-guide/filtering/
As you can see this protection is provided by default: https://github.com/encode/django-rest-framework/blob/c10f2266222c434485889b08cc1463acdb8fa169/rest_framework/fields.py#L739

Reject null input for safe apps filters

---

docker-compose.yml

Closes https://github.com/safe-global/safe-config-service/issues/728
- If no environment variables are not set (more specifically `NGINX_HOST_PORT`, `POSTGRES_PORT` and `DOCKER_NGINX_VOLUME_ROOT`) then docker-compose fails to start the containers
- Even though the variables are set as an example in `.dev.env` which is read by `env_file`, those variables will only be available to the container and not to the docker-compose.yml file

Add default environment variables to docker-compose

---

.github/workflows/test.yml
src/about/tests/test_views.py
src/version.py

Release: https://github.com/safe-global/safe-config-service/releases/tag/v2.46.0
Regarding [1629182](https://github.com/safe-global/safe-config-service/pull/783/commits/1629182f5e6f945df4788dd4d7bc6886179dabe7):
We now install the dependencies set in the requirement file for `flake8`, `isort` and `black` jobs. They were using the latest version available which could cause the pipeline to fail even though the project matches and is compliant with the version set under `requirements-dev.txt`

Backmerge release 2.46.0

---

.github/workflows/test.yml

- In addition to `linux/amd64` images, build and upload `linux/arm64` images to DockerHub
- Add QEMU step to support targeting multiple platforms in the build process

Build and upload arm64 images

---

requirements.txt

This revert is needed because some incompatibilities are breaking Swagger UI view.
- Reverts https://github.com/safe-global/safe-config-service/pull/880
- Wait for https://github.com/axnsan12/drf-yasg/issues/856 to be released
FYI: (Same scenario in https://github.com/safe-global/safe-transaction-service/pull/1531)

Revert "Bump drf-yasg[validation] from 1.21.5 to 1.21.6"

---

.github/workflows/test.yml
requirements-dev.txt

- Removes `coveralls` from the project.
- Uses the official GitHub action from Coveralls – https://github.com/coverallsapp/github-action

Remove coveralls dependency

---

.dev.env
src/chains/signals.py
src/chains/tests/test_signals.py
src/clients/safe_client_gateway.py
src/config/settings.py
src/safe_apps/signals.py
src/safe_apps/tests/test_signals.py

Closes #898 
This PR:
- Adds `ALTERNATIVE_CGW_URL` and `ALTERNATIVE_CGW_FLUSH_TOKEN` as environment variables to the service settings.
- If these variables are set, it makes the service execute a second HTTP request to `${ALTERNATIVE_CGW_URL}/v2/flush`, in order to invalidate the cache in a second Client Gateway pointed by that URL.
- Modifies the `test_signals` unit tests accordingly to verify the expected requests are executed.

Support a second Client Gateway URL

---

src/config/settings.py

This PR:
- Adds an optional `MEDIA_URL` environment variable to be configured for the service local setup. This won't alter the behavior of the service when using S3 assets storage.

Make MEDIA_URL configurable

---

.dev.env
src/clients/safe_client_gateway.py
src/config/settings.py

- Sets a timeout when connecting to the Safe Client Gateway.
- The timeout is configurable with the environment variable `CGW_SESSION_TIMEOUT_SECONDS`. If it's not set, 2 seconds will be used.
- The maximum number of retries is now configurable under `CGW_SESSION_MAX_RETRIES`. If it's not set, no retries will be made (0).

Set timeout when connecting to the CGW

---

src/chains/signals.py
src/chains/tests/test_signals.py
src/chains/tests/test_signals_ff_hook_events.py
src/clients/safe_client_gateway.py
src/config/settings.py
src/safe_apps/signals.py
src/safe_apps/tests/test_signals.py
src/safe_apps/tests/test_signals_ff_hook_events.py

Reference: https://github.com/safe-global/safe-client-gateway/issues/682
- Refactors the WebHook hook logic for the Safe Client Gateway client.
- A WebHook event is now represented as a `@dataclass` – `HookEvent`. This `HookEvent` can have two types:
* `CHAIN_UPDATE` – represents chain related updates (more specifically updates to `Chain`, `GasPrice`, `Feature` – chain feature, and `Wallet`).
* `SAFE_APPS_UPDATE` – represents safe app related updates (more specifically updates to `SafeApp`, `Provider`, `Tag` and `Feature` – safe app feature).
- The new web hooks are under a feature preview and can be enabled by setting the environment variable `FF_HOOK_EVENTS` to `true`.
* If `FF_HOOK_EVENTS` is set to `false`, the `/v2/flush` endpoint is triggered (as before).

Add Hook Events for Chains and Safe Apps

---

Dockerfile

Changes:
- Create, assign permissions, and run the application Docker container using a non-root user.

Run container as non-root user

---

Dockerfile

Changes:
- Removes `tini` from docker container build dependencies, as this is not needed anymore.

Remove tini docker container dependency

---

Dockerfile

Instead of copying the entire directory, copy only the required files:
- `/src` directory which contains the source code of the service
- `/static` directory which contains the required static files
- `docker-entrypoint.sh` which is the script to be used to start up the service.

Reduce file/folder copying scope

---

.dev.env
src/chains/tests/test_signals.py
src/clients/safe_client_gateway.py
src/config/settings.py
src/safe_apps/tests/test_signals.py

Depends on #1026 
Changes:
- Renames `CGW_FLUSH_TOKEN` to `CGW_AUTH_TOKEN` on several files.

Rename CGW_FLUSH_TOKEN to CGW_AUTH_TOKEN

---

.dev.env
src/config/settings.py

This PR introduces `USE_PROXY_SSL_HEADER` environment variable to the project.
When set to `true`, this variable enables the use of the `HTTP_X_FORWARDED_PROTO` header for secure request detection in case the application is behind a proxy. This helps control Django's `is_secure()` method behavior, in scenarios where SSL termination occurs at the proxy level.
These changes are backward compatible and should not affect existing deployments unless the environment variable is explicitly set.
- Reported Issue: https://github.com/safe-global/safe-config-service/issues/634
- Django: https://docs.djangoproject.com/en/5.0/ref/settings/#secure-proxy-ssl-header

Introduce USE_PROXY_SSL_HEADER environment variable

---

.pre-commit-config.yaml

- The pre-commit configuration was using Flake8 version 6.0.0 while the project version is 7.0.0.
- This led to a mismatch of linter errors for environments using the pre-commit setup and the ones not using it (e.g., GitHub Actions).

Bumps Flake8 version in pre-commit

---

src/chains/serializers.py
src/chains/tests/test_models.py

For Free gas networks like GoQuorum, we need `fixed_wei_value` to be set to zero. However, the serializer check doesnt handle 0 for fixed types & raises `APIException` exception.
```sql
postgres=# select * from chains_gasprice;
-[ RECORD 1 ]------------+------------
id                       | 1
oracle_uri               | 
oracle_parameter         | 
gwei_factor              | 1.000000000
fixed_wei_value          | 0
rank                     | 100
chain_id                 | 
max_fee_per_gas          | 
max_priority_fee_per_gas | 
```
`/api/v1/chains/:chainId/`
```json
{ "detail":"The gas price oracle or a fixed gas price was not provided for chain" }
```
This PR modifies the check to `is not None` to allow for zero values
`/api/v1/chains/:chainId/`
```json
{
...,
"gasPrice": [
{
"type": …
```

fix: handle 0 as fixed gas fee

---

src/safe_apps/models.py
src/safe_apps/tests/test_models.py

Closes #1100 
This PR fixes a bug in the `SafeApp` creation flow. As `SafeApp` is not persisted to the database yet when `safe_app_icon_path` is executed, it has no access to the `app_id` field (as it depends on the database PK). So this field cannot be used directly as part of the file URL. As a result, before this PR, `None` was being appended to the URL instead of the app ID.
- Generate logo URLs by calling `uuid.uuid4()` instead of relying on the Safe App ID.

Fix invalid iconUrl on Safe App creation

---

src/config/settings.py
src/safe_apps/models.py
src/safe_apps/tests/test_views.py
src/safe_apps/views.py

This PR adds an optional query parameter to `/safe-apps/` endpoint to manage the visibility filter.
- Adds `onlyListed` query parameter. When it's `false`, both `visible: true` and `visible: false` Safe Apps are returned in the endpoint response. When it's `true` only `visible: true` Safe Apps are returned.

Add optional "onlyListed" query param for SafeApps filtering

---

src/clients/safe_client_gateway.py

The function `urljoin` from `urllib.parse` expect a `base` and a `url` to concat. 
As the path being concatenated to `CGW_URL` is `/v1/hooks/events`, the function `urljoin` interprets `url` as a base domain, and splits out any path it can have. This causes problems when the base URL does contain paths, as those are split out.
- The URL being added to `CGW_URL` is now `v1/hooks/events`, and the `/` URL separator is concatenated to the `base` conditionally (to avoid separator duplications).

Allow URL paths on CGW_URL

---

requirements.txt

- Reverts `boto3` library upgraded on https://github.com/safe-global/safe-config-service/pull/1212 to `1.34.158`

Revert boto3 upgrade to 1.34.158

---

requirements.txt

- Reverts `django` version upgrade from https://github.com/safe-global/safe-config-service/pull/1203 back to `5.0.8`

Revert django upgrade back to 5.0.8

---

requirements.txt

Our `django-check` job is currently failing after install ([example](https://github.com/safe-global/safe-config-service/actions/runs/10560766575/job/29254970812?pr=1220)). This stems from the related version of the web3 package for safe-eth-py. The offending error is:
```sh
ImportError: cannot import name 'geth_poa_middleware' from 'web3.middleware'
```
When transitioning from version 6 to 7, web3 [renamed some middleware](https://web3py.readthedocs.io/en/stable/migration.html#middleware-renaming-and-removals), including `get_poa_middleware`. Our safe-eth-py package has [yet to migrate to version 7](https://github.com/safe-global/safe-eth-py/issues/1324), however. It therefore tries to import the non-existent `get_poa_middleware`.
This pins the web3 package in accordance with the …

Pin web3 to 6.20.2

---

src/safe_apps/admin.py

Resolves #984
This PR makes the chain_ids fields in the admin UI display a multiple choice select and it retrieves the allowed chain ids and chain names from the Chains app.

Feat(Safe Apps): admin chains with names

---

README.md

In order to run the project locally, `setuptools` needs to be installed. This adds the command to the setup guide in the README.
- Add `pip install setuptools` command to README.

Add install command to README

---

.github/workflows/cla.yml

Resolves #1266
"It is preferable to use a general CLA repo to store signatures as we do in other repos"
This changes the CLA workflow to store signatures in our respective org. repo.
- Set `remote-organization-name` to `'safe-global'`
- Set `remote-repository-name` to `'cla-signatures'`

Store CLA signatures in org. repo.

---

.github/workflows/cla.yml

- Changes `PERSONAL_ACCESS_TOKEN` to `CLA_ACCESS_TOKEN` in the CLA Assistant Github Action.

Fix bad CLA_ACCESS_TOKEN reference
